[workspace]
members = [
    "crabsoup-lua",
]
resolver = "2"

[profile.dev]
opt-level = 's'

[profile.release]
opt-level = 3
lto = true

[workspace.dependencies]
anyhow = "1.0"
glob = "0.3"
mlua = { version = "0.9", features = ["async", "luau-jit", "send"] }
rustyline = { version = "14.0", default-features = false }
tracing = "0.1"
wyrand = { version = "0.2", features = ["wyhash"] }

# HTML DOM related
ego-tree = "0.6"
html5ever = "0.26"
scraper = { version = "0.19", features = ["atomic", "deterministic"] }
